version: 2
jobs:
  build-wasm:
    docker:
      - image: circleci/rust:latest-node-browsers
    working_directory: ~/repo

    steps:
      - checkout
      # Install wasm-pack
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      # Build the game-of-life wasm package
      - run: cd src/pkg/game-of-life/rust && wasm-pack build --release --out-name index

      # Workspace the built files
      - persist_to_workspace:
        root: src
        paths:
          - pkg/game-of-life/rust/pkg/*

  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
        at: /tmp/workspace

      - run: ls /tmp/workspace

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      # - run: yarn install

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}

      # # run tests!
      # - run: yarn test

workflows:
  version: 2

  btd:
    jobs:
      - build-wasm
      - deploy:
        requires:
          build-wasm
